-- Ensure IDs auto-generate on PostgreSQL after MySQL import
DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='sessions' AND column_name='id') THEN
    ALTER TABLE public.sessions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
EXCEPTION WHEN others THEN
  -- ignore if already identity
  NULL;
END $$;

DO $$
BEGIN
  IF EXISTS (SELECT 1 FROM information_schema.columns WHERE table_schema='public' AND table_name='users' AND column_name='id') THEN
    ALTER TABLE public.users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
EXCEPTION WHEN others THEN
  NULL;
END $$;

SELECT setval(pg_get_serial_sequence('public.sessions','id'), COALESCE((SELECT MAX(id) FROM public.sessions), 1), true);
SELECT setval(pg_get_serial_sequence('public.users','id'), COALESCE((SELECT MAX(id) FROM public.users), 1), true);
