-- 1) Make integer primary key columns auto-generated (PostgreSQL identity)
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT c.table_name
    FROM information_schema.columns c
    JOIN information_schema.table_constraints tc
      ON tc.table_schema = c.table_schema
     AND tc.table_name = c.table_name
     AND tc.constraint_type = 'PRIMARY KEY'
    JOIN information_schema.key_column_usage kcu
      ON kcu.table_schema = tc.table_schema
     AND kcu.table_name = tc.table_name
     AND kcu.constraint_name = tc.constraint_name
     AND kcu.column_name = c.column_name
    WHERE c.table_schema = 'public'
      AND c.column_name = 'id'
      AND c.data_type = 'integer'
  LOOP
    BEGIN
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY', r.table_name);
    EXCEPTION WHEN others THEN
      NULL;
    END;
  END LOOP;
END $$;

-- 2) Convert imported smallint flags back to boolean
DO $$
DECLARE r record;
BEGIN
  FOR r IN
    SELECT * FROM (
      VALUES
        ('ekstrakurikuler','is_active','true'),
        ('testimonials','is_approved','false'),
        ('testimonials','is_featured','false'),
        ('features','is_active','true'),
        ('hero','is_active','true'),
        ('visi_misi','is_active','true'),
        ('environment_features','is_active','true'),
        ('principal_welcome','is_active','true'),
        ('personal_approach','is_active','true'),
        ('osis','is_active','true'),
        ('guru_dan_staf','is_active','true'),
        ('blog_news','is_published','false'),
        ('blog_news','is_active','true')
    ) AS t(table_name, column_name, def)
  LOOP
    IF EXISTS (
      SELECT 1
      FROM information_schema.columns
      WHERE table_schema='public'
        AND table_name=r.table_name
        AND column_name=r.column_name
        AND data_type='smallint'
    ) THEN
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I DROP DEFAULT', r.table_name, r.column_name);
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I TYPE boolean USING (%I <> 0)', r.table_name, r.column_name, r.column_name);
      EXECUTE format('ALTER TABLE public.%I ALTER COLUMN %I SET DEFAULT %s', r.table_name, r.column_name, r.def);
    END IF;
  END LOOP;
END $$;

-- 3) Create public storage bucket for uploads (if not exists)
INSERT INTO storage.buckets (id, name, public)
VALUES ('public-uploads', 'public-uploads', true)
ON CONFLICT (id) DO NOTHING;
