DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='testimonials' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.testimonials ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
EXCEPTION WHEN others THEN
  NULL;
END $$;

DO $$
BEGIN
  IF EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema='public' AND table_name='school_information' AND column_name='id' AND is_identity='NO'
  ) THEN
    ALTER TABLE public.school_information ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
  END IF;
EXCEPTION WHEN others THEN
  NULL;
END $$;
